export const REGISTRE_SUCCESS = "REGISTRE_SUCCESS";
export const REGISTRE_FAIL = "REGISTRE_FAIL";
export const REGISTRE_LOADING = "REGISTRE_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";

export const LOGOUT = "LOGOUT";